# Generated by Django 5.2.1 on 2025-05-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_book_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='capa_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
